import type { GridColDef } from "@mui/x-data-grid"
import type { IPlayerColumn } from "../../store/playerFilter.store"

export const playerColumns: GridColDef<IPlayerColumn>[] = [
  { field: "can_transact", headerName: "Can Transact", width: 150 },
  { field: "web_name", headerName: "Name", width: 150 },
  { field: "teamName", headerName: "Team", width: 150 },
  { field: "position", headerName: "Position", width: 100 },
  {
    field: "chance_of_playing_next_round",
    headerName: "Chance of Playing Next Round",
    width: 200,
  },
  { field: "total_points", headerName: "Total Points", width: 150 },
  { field: "score", headerName: "Score", width: 150 },
  { field: "now_cost", headerName: "Cost", width: 100 },
  {
    field: "",
    headerName: "Minutes per 90",
    width: 100,
    renderCell: ({ row }) => (row.minutes / row.starts).toFixed(0),
  },
  { field: "points_per_game", headerName: "Points per Game", width: 150 },
  { field: "selected_by_percent", headerName: "Selected By (%)", width: 150 },
  {
    field: "ep_next",
    headerName: "Expected points - Next",
    width: 200,
  },
  {
    field: "transfers_out_event",
    headerName: "Transfers Out (Event)",
    width: 200,
  },
  { field: "value_form", headerName: "Value Form", width: 150 },
  { field: "value_season", headerName: "Value Season", width: 150 },
  { field: "minutes", headerName: "Minutes Played", width: 150 },
  { field: "goals_scored", headerName: "Goals Scored", width: 150 },
  { field: "assists", headerName: "Assists", width: 100 },
  { field: "clean_sheets", headerName: "Clean Sheets", width: 150 },
  { field: "goals_conceded", headerName: "Goals Conceded", width: 150 },
  { field: "own_goals", headerName: "Own Goals", width: 100 },
  { field: "penalties_saved", headerName: "Penalties Saved", width: 150 },
  { field: "penalties_missed", headerName: "Penalties Missed", width: 150 },
  { field: "yellow_cards", headerName: "Yellow Cards", width: 100 },
  { field: "red_cards", headerName: "Red Cards", width: 100 },
  { field: "saves", headerName: "Saves", width: 100 },
  { field: "bonus", headerName: "Bonus", width: 100 },
  { field: "bps", headerName: "BPS", width: 100 },
  { field: "influence", headerName: "Influence", width: 100 },
  { field: "creativity", headerName: "Creativity", width: 100 },
  { field: "threat", headerName: "Threat", width: 100 },
  { field: "ict_index", headerName: "ICT Index", width: 100 },
  { field: "expected_goals", headerName: "Expected Goals", width: 150 },
  { field: "expected_assists", headerName: "Expected Assists", width: 150 },
  {
    field: "expected_goal_involvements",
    headerName: "Expected Goal Involvements",
    width: 200,
  },
  {
    field: "expected_goals_conceded",
    headerName: "Expected Goals Conceded",
    width: 200,
  },
  { field: "starts", headerName: "Starts", width: 100 },
  {
    field: "expected_goals_per_90",
    headerName: "Expected Goals per 90",
    width: 180,
  },
  {
    field: "expected_assists_per_90",
    headerName: "Expected Assists per 90",
    width: 180,
  },
  {
    field: "expected_goal_involvements_per_90",
    headerName: "Expected Goal Involvements per 90",
    width: 220,
  },
  {
    field: "expected_goals_conceded_per_90",
    headerName: "Expected Goals Conceded per 90",
    width: 220,
  },
  {
    field: "goals_conceded_per_90",
    headerName: "Goals Conceded per 90",
    width: 180,
  },
  { field: "saves_per_90", headerName: "Saves per 90", width: 120 },
  { field: "starts_per_90", headerName: "Starts per 90", width: 120 },
  {
    field: "clean_sheets_per_90",
    headerName: "Clean Sheets per 90",
    width: 150,
  },
  { field: "influence_rank", headerName: "Influence Rank", width: 120 },
  { field: "creativity_rank", headerName: "Creativity Rank", width: 120 },
  { field: "threat_rank", headerName: "Threat Rank", width: 120 },
  { field: "ict_index_rank", headerName: "ICT Index Rank", width: 120 },
  { field: "now_cost_rank", headerName: "Cost Rank", width: 100 },
  { field: "form_rank", headerName: "Form Rank", width: 100 },
  {
    field: "points_per_game_rank",
    headerName: "Points per Game Rank",
    width: 150,
  },
  { field: "selected_rank", headerName: "Selected Rank", width: 120 },
  { field: "transfers_in", headerName: "Transfers In", width: 120 },
  {
    field: "transfers_in_event",
    headerName: "Transfers In (Event)",
    width: 150,
  },
  { field: "transfers_out", headerName: "Transfers Out", width: 120 },
  { field: "dreamteam_count", headerName: "Dream Team Count", width: 150 },
  { field: "in_dreamteam", headerName: "In Dream Team", width: 120 },
  { field: "news", headerName: "News", width: 200 },
  { field: "status", headerName: "Status", width: 100 },
  { field: "form", headerName: "Form", width: 100 },
  { field: "first_name", headerName: "First Name", width: 120 },
  { field: "second_name", headerName: "Second Name", width: 120 },
  { field: "code", headerName: "Code", width: 80 },
  { field: "cost_change_event", headerName: "Cost Change Event", width: 150 },
  {
    field: "cost_change_event_fall",
    headerName: "Cost Change Event Fall",
    width: 180,
  },
  { field: "cost_change_start", headerName: "Cost Change Start", width: 150 },
  {
    field: "cost_change_start_fall",
    headerName: "Cost Change Start Fall",
    width: 180,
  },
  { field: "region", headerName: "Region", width: 100 },
  { field: "team_code", headerName: "Team Code", width: 100 },
  { field: "event_points", headerName: "Event Points", width: 120 },
  { field: "selected_rank_type", headerName: "Selected Rank Type", width: 150 },
  {
    field: "influence_rank_type",
    headerName: "Influence Rank Type",
    width: 150,
  },
  {
    field: "creativity_rank_type",
    headerName: "Creativity Rank Type",
    width: 150,
  },
  { field: "threat_rank_type", headerName: "Threat Rank Type", width: 150 },
  {
    field: "ict_index_rank_type",
    headerName: "ICT Index Rank Type",
    width: 150,
  },
  { field: "now_cost_rank_type", headerName: "Cost Rank Type", width: 120 },
  { field: "form_rank_type", headerName: "Form Rank Type", width: 120 },
  {
    field: "points_per_game_rank_type",
    headerName: "Points per Game Rank Type",
    width: 180,
  },
  {
    field: "direct_freekicks_order",
    headerName: "Direct Freekicks Order",
    width: 180,
  },
  {
    field: "direct_freekicks_text",
    headerName: "Direct Freekicks Text",
    width: 180,
  },
  { field: "penalties_order", headerName: "Penalties Order", width: 150 },
  { field: "penalties_text", headerName: "Penalties Text", width: 150 },
  {
    field: "corners_and_indirect_freekicks_order",
    headerName: "Corners & Indirect Freekicks Order",
    width: 220,
  },
  {
    field: "corners_and_indirect_freekicks_text",
    headerName: "Corners & Indirect Freekicks Text",
    width: 220,
  },
  {
    field: "defensive_contribution",
    headerName: "Defensive Contribution",
    width: 180,
  },
  { field: "ep_this", headerName: "Expected Points - This", width: 180 },
  { field: "news_added", headerName: "News Added", width: 120 },
  { field: "photo", headerName: "Photo", width: 100 },
  { field: "removed", headerName: "Removed", width: 100 },
  { field: "special", headerName: "Special", width: 100 },
  { field: "squad_number", headerName: "Squad Number", width: 120 },
  { field: "team_join_date", headerName: "Team Join Date", width: 140 },
  { field: "birth_date", headerName: "Birth Date", width: 120 },
  { field: "has_temporary_code", headerName: "Has Temporary Code", width: 160 },
  { field: "opta_code", headerName: "Opta Code", width: 120 },
]
